# Site settings
title: Startup Consulting
email: shane.kercheval@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
    Simple blog about ideas and strategy.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://shanekercheval.me" # the base hostname & protocol for your site
twitter_username: shanekercheval

# Build settings
markdown: kramdown
permalink: /:title

# http://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Shane Kercheval
      layout: post
      categories: strategy
