# Site settings
title: Startup Consulting
owner: Shane Kercheval
email: shane.kercheval@yahoo.com
description: > # this means to ignore newlines
    Have an idea?<br>
    I help first-time entrepreneurs strategize and launch.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shanekercheval.me" # the base hostname & protocol for your site
twitter_username: shanekercheval

# Build settings
markdown: kramdown
permalink: /:title

# http://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: Shane Kercheval
      comments: true
