# Site settings
title: Startup Consulting
owner: Shane Kercheval
description: > # this means to ignore newlines
    Have an idea? I help first-time entrepreneurs strategize and launch.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "127.0.0.1"
url: "http://shanekercheval.me" # the base hostname & protocol for your site
logo: "/img/logo.png"

# Build settings
markdown: kramdown

# http://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: Shane Kercheval
      comments: true
      permalink: /blog/:title/
